{
  "opcode_to_type": {
    "1": "Unknown",
    "15": "MemoryRead",
    "18": "Unknown",
    "6": "Unknown",
    "16": "MemoryRead",
    "8": "Unknown",
    "20": "Unknown",
    "2": "Unknown",
    "3": "Unknown",
    "13": "Unknown",
    "4": "Return",
    "12": "Unknown",
    "14": "MemoryRead",
    "19": "Unknown",
    "11": "MemoryRead",
    "7": "Unknown",
    "5": "MemoryWrite",
    "10": "Unknown",
    "17": "Unknown",
    "0": "Unknown",
    "9": "Unknown"
  },
  "opcode_to_name": {
    "19": "OP_19_Unknown",
    "14": "OP_14_MemoryRead",
    "9": "OP_9_Unknown",
    "4": "OP_4_Return",
    "0": "OP_0_Unknown",
    "10": "OP_10_Unknown",
    "11": "OP_11_MemoryRead",
    "3": "OP_3_Unknown",
    "2": "OP_2_Unknown",
    "18": "OP_18_Unknown",
    "13": "OP_13_Unknown",
    "16": "OP_16_MemoryRead",
    "1": "OP_1_Unknown",
    "5": "OP_5_MemoryWrite",
    "12": "OP_12_Unknown",
    "15": "OP_15_MemoryRead",
    "17": "OP_17_Unknown",
    "7": "OP_7_Unknown",
    "20": "OP_20_Unknown",
    "6": "OP_6_Unknown",
    "8": "OP_8_Unknown"
  },
  "state_property_names": {
    "memory_prop": "W",
    "pointer_prop": null,
    "accumulator_prop": "c"
  },
  "heuristics_applied": []
}